//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string username { get; set; }
        public string upass { get; set; }
        public string uName { get; set; }
        public string uPhone { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public string uRole { get; set; }
        public Nullable<byte> Status { get; set; }
    }
}
